function schema = condition_schema()
%CONDITION_SCHEMA Central definitions for GUI/table units and config mapping.
%   SCHEMA fields describe existing config controls. No PV parameter exists.
schema.names = {'No','InputWAV','CPA_m','SourceVelocityKmh', ...
    'ReceiverVelocityKmh','Profile','SourceAccelerationMps2', ...
    'ReceiverAccelerationMps2','DurationSec','GroundReflectionCoeff', ...
    'Obstacle','ObstacleCount','Seed','Diffraction','Reflection'};
schema.labels = {'No','入力WAV','水平間隔 CPA [m]','Source [km/h]', ...
    'Receiver [km/h]','速度プロファイル','Source a [m/s²]', ...
    'Receiver a [m/s²]','時間 [s]','地面反射係数', ...
    '障害物','個数','Seed','回折','反射'};
schema.profiles = {'constant_velocity','constant_acceleration'};
schema.logicalNames = {'Obstacle','Diffraction','Reflection'};
schema.numericNames = setdiff(schema.names, ...
    [{'InputWAV','Profile'},schema.logicalNames],'stable');
end

